
      
unsecured:
       resources:
         - /swagger-ui/**
         - /v3/api-docs/**
         - /api/unsecured/**
         - /token/*   
         
         
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://dev-11059713.okta.com/oauth2/default/v1/token
            issuer-uri: https://dev-11059713.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oa4j6vyzvKBu4gZ85d7
            client-secret: 73wXno9YxvW3RPam8Fj00PDXYrHrtakvFnOEE295
            authorization-grant-type: client_credentials
            scope: custom_mod
            
#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          okta:
#            token-uri: https://login-uat.rhythmsynergy.com/oauth2/default/v1/token
#            issuer-uri: https://login-uat.rhythmsynergy.com/oauth2/default
#        registration:
#          okta:
#            client-id: 0oa1p7y26atYDWs7J1d7
#            client-secret: WBhbCFa_y2OWiUi6fahB-q-1zsaMazKaWnq37cxC
#            authorization-grant-type: client_credentials
#            scope: api_access
        
            
            

    