
      
unsecured:
       resources:
         - /swagger-ui/**
         - /v3/api-docs/**
         - /api/unsecured/**
         - /token/*   
         
         
spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://dev-11059713.okta.com/oauth2/default/v1/token
            issuer-uri: https://dev-11059713.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oa4j6vyzvKBu4gZ85d7
            client-secret: 73wXno9YxvW3RPam8Fj00PDXYrHrtakvFnOEE295
            authorization-grant-type: client_credentials
            scope: custom_mod
            

        
springdoc:
    api-docs:
      enabled: true          
    paths-to-exclude: /swagger-resources/**
    packagesToScan: com.rhythm.integration
    
